SELECT ALL EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.FIRST_NAME, EMPLOYEES.EMAIL, EMPLOYEES.PHONE_NUMBER, 
EMPLOYEES.JOB_ID, EMPLOYEES.SALARY, TO_CHAR(EMPLOYEES.HIRE_DATE,'DD/MM/YYYY') P_DATE
FROM EMPLOYEES
ORDER BY EMPLOYEES.EMPLOYEE_ID ASC 



SELECT * FROM EMPLOYEES WHERE EMP_


SELECT A.DEPARTMENT_ID,A.DEPARTMENT_NAME , B.EMPLOYEE_ID,B.FIRST_NAME,B.SALARY,B.HIRE_DATE,B.JOB_ID 
FROM DEPARTMENTS A, EMPLOYEES B
WHERE A.DEPARTMENT_ID=B.DEPARTMENT_ID;


select D.department_id, D.department_name, E.employee_id, E.first_name, E.job_id, E.Salary, E.Hire_date 
from departments D, employees E
where D.department_id=E.DEPARTMENT_ID;


SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, E.EMPLOYEE_ID, E.FIRST_NAME, E.JOB_ID, E.SALARY, E.HIRE_DATE 
FROM DEPARTMENTS D, EMPLOYEES E
WHERE D.DEPARTMENT_ID=E.DEPARTMENT_ID;