SELECT COMPANY_CODE,ITEM_CODE,ITEM_NAME,CAT_CODE,CAT_DESC,TYPE_CODE,TYPE_DESC,NVL(SUM(PO_RCV),0) RECEIVEING_QTY,NVL(SUM(ISSUE),0) CONSUMPTION,NVL(SUM(WORKSHOP_RCV),0) TRASNFER_RCV,
NVL(SUM(CONSUMPTION),0) TRANSFER_ISSUE,ITEM_UOM,LOC_CODE
FROM(
SELECT  DISTINCT A.COMPANY_CODE,A.ITEM_CODE,B.ITEM_NAME,B.CAT_CODE,B.CAT_DESC,B.TYPE_CODE,B.TYPE_DESC, 0 PO_RCV,0 ISSUE,0 WORKSHOP_RCV ,0 CONSUMPTION,ITEM_UOM,A.LOC_CODE
FROM INV_ITEM_LEDGER A,INV_ITEM_VW B,INV_ORG_VW D
WHERE TO_CHAR(A.TRANS_DATE,'RRRRMM')=TO_CHAR(ADD_MONTHS((LAST_DAY(:P_FROM_DATE)),-1),'RRRRMM')
AND A.ITEM_CODE=NVL(:P_ITEM_CODE,A.ITEM_CODE)
AND A.COMPANY_CODE=:P_COMPANY_CODE
AND B.CAT_CODE=NVL(:P_CAT_CODE,B.CAT_CODE)
AND B.TYPE_CODE=NVL(:P_TYPE_CODE,B.TYPE_CODE)
AND (D.REF_ORG_CODE=NVL(:P_ORG_CODE,D.REF_ORG_CODE) OR A.ORG_CODE=NVL(:P_ORG_CODE,A.ORG_CODE))
AND A.LOC_CODE=DECODE(:P_LOC_CODE,'ALL_LOC',A.LOC_CODE,:P_LOC_CODE)
AND A.ITEM_CODE=B.ITEM_CODE
AND A.COMPANY_CODE=B.COMPANY_CODE
AND A.COMPANY_CODE=D.COMPANY_CODE
AND A.ORG_CODE=D.ORG_CODE
UNION ALL
SELECT A.COMPANY_CODE,A.ITEM_CODE,B.ITEM_NAME,B.CAT_CODE,B.CAT_DESC,B.TYPE_CODE,B.TYPE_DESC,
SUM(CASE WHEN A.DRCR_FLAG='DR' AND A.TYPE_TRANS_NO  IN('POR','FGR','MIR','LCR','EXA','COR','PFR','VHR','WCR','OFR','EMR','CVR','SRR') THEN A.TRANS_QTY
 WHEN A.DRCR_FLAG='CR' AND A.TYPE_TRANS_NO  IN('TFA') THEN A.TRANS_QTY*(-1) ELSE 0 END) PO_RCV,
SUM(CASE WHEN A.DRCR_FLAG='CR' AND A.TYPE_TRANS_NO NOT IN ('WOT','FGT','TFA','LOT','LET') THEN A.TRANS_QTY ELSE 0 END) CONSUMPTION,
SUM(CASE WHEN A.DRCR_FLAG='DR' AND A.TYPE_TRANS_NO IN ('WOT','PRI','FGT','LET','LOT') THEN A.TRANS_QTY ELSE 0 END) TRANSFER_RCV,
SUM(CASE WHEN A.DRCR_FLAG='CR' AND A.TYPE_TRANS_NO IN ('WOT','FGT','LET','LOT') THEN A.TRANS_QTY ELSE 0 END) TRANSFER_ISSUE,B.ITEM_UOM,A.LOC_CODE
FROM INV_ITEM_LEDGER A,INV_ITEM_VW B,INV_ORG_VW D
WHERE TO_DATE(TRANS_DATE,'DD/MM/RRRR') BETWEEN :P_FROM_DATE AND  :P_TO_DATE
AND A.ITEM_CODE =nvl(:P_ITEM_CODE,A.ITEM_CODE)
AND  A.COMPANY_CODE=:P_COMPANY_CODE
AND (D.REF_ORG_CODE=NVL(:P_ORG_CODE,D.REF_ORG_CODE) OR A.ORG_CODE=NVL(:P_ORG_CODE,A.ORG_CODE))
AND A.LOC_CODE=DECODE(:P_LOC_CODE,'ALL_LOC',A.LOC_CODE,:P_LOC_CODE)
AND B.CAT_CODE=NVL(:P_CAT_CODE,B.CAT_CODE)
AND B.TYPE_CODE=NVL(:P_TYPE_CODE,B.TYPE_CODE)
AND A.ITEM_CODE=B.ITEM_CODE
AND A.COMPANY_CODE=B.COMPANY_CODE
AND A.COMPANY_CODE=D.COMPANY_CODE
AND A.ORG_CODE=D.ORG_CODE
GROUP BY A.COMPANY_CODE,A.ITEM_CODE,B.ITEM_NAME,D.REF_ORG_CODE,B.CAT_CODE,B.CAT_DESC,B.TYPE_CODE,B.TYPE_DESC,B.ITEM_UOM,A.LOC_CODE)
GROUP BY COMPANY_CODE,ITEM_CODE,ITEM_NAME,CAT_CODE,CAT_DESC,TYPE_CODE,TYPE_DESC,ITEM_UOM,LOC_CODE
ORDER BY ITEM_NAME ASC

select loc_code, store_name ||', '|| floor_loc || ', '|| Reck_no ||', '|| Bin_no
from inv_item_loc

select decode(house_no,null,null,house_no ||', ')||
 decode(road_no,null,null, road_no ||', ')||
 decode(area,null,null,area||', ')||
 decode(city,null,null,city||', ')||
 decode(post_code,null,null,post_code||', ')||
 decode(country,null,null,country)
 from abc_company_vw
 
select 
loc_code, 
decode(store_name,null,null,store_name)||
decode(floor_loc,null,null,','||floor_loc)|| 
decode(Reck_no,null,null,','||Reck_no) ||
decode(Bin_no,null,null,','||Bin_no)
from inv_item_loc


function CF_Loc_NameFormula return Char is
v_name varchar2(200);
begin
return
decode(store_name,null,null,store_name)||
decode(floor_loc,null,null,','||floor_loc)|| 
decode(Reck_no,null,null,','||Reck_no) ||
decode(Bin_no,null,null,','||Bin_no)
into v_name
from inv_item_loc
where
loc_code=:p_loc_code;
end;